////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace SocialMedia.PL.Language {
//    using System;
    
    
//    /// <summary>
//    ///   A strongly-typed resource class, for looking up localized strings, etc.
//    /// </summary>
//    // This class was auto-generated by the StronglyTypedResourceBuilder
//    // class via a tool like ResGen or Visual Studio.
//    // To add or remove a member, edit your .ResX file then rerun ResGen
//    // with the /str option, or rebuild your VS project.
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    public class Resource {
        
//        private static global::System.Resources.ResourceManager resourceMan;
        
//        private static global::System.Globalization.CultureInfo resourceCulture;
        
//        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
//        internal Resource() {
//        }
        
//        /// <summary>
//        ///   Returns the cached ResourceManager instance used by this class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        public static global::System.Resources.ResourceManager ResourceManager {
//            get {
//                if (object.ReferenceEquals(resourceMan, null)) {
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialMedia.PL.Language.Resource", typeof(Resource).Assembly);
//                    resourceMan = temp;
//                }
//                return resourceMan;
//            }
//        }
        
//        /// <summary>
//        ///   Overrides the current thread's CurrentUICulture property for all
//        ///   resource lookups using this strongly typed resource class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        public static global::System.Globalization.CultureInfo Culture {
//            get {
//                return resourceCulture;
//            }
//            set {
//                resourceCulture = value;
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to About.
//        /// </summary>
//        public static string About {
//            get {
//                return ResourceManager.GetString("About", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Accept.
//        /// </summary>
//        public static string Accept {
//            get {
//                return ResourceManager.GetString("Accept", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Actions.
//        /// </summary>
//        public static string Actions {
//            get {
//                return ResourceManager.GetString("Actions", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Add New Job.
//        /// </summary>
//        public static string Add_New_Job {
//            get {
//                return ResourceManager.GetString("Add New Job", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to AllUsers.
//        /// </summary>
//        public static string AllUsers {
//            get {
//                return ResourceManager.GetString("AllUsers", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Archive.
//        /// </summary>
//        public static string Archive {
//            get {
//                return ResourceManager.GetString("Archive", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Archived Posts.
//        /// </summary>
//        public static string Archived_Posts {
//            get {
//                return ResourceManager.GetString("Archived Posts", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Assign.
//        /// </summary>
//        public static string Assign {
//            get {
//                return ResourceManager.GetString("Assign", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Assign New Role.
//        /// </summary>
//        public static string Assign_New_Role {
//            get {
//                return ResourceManager.GetString("Assign New Role", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Back.
//        /// </summary>
//        public static string Back {
//            get {
//                return ResourceManager.GetString("Back", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Back to All Jobs.
//        /// </summary>
//        public static string Back_to_All_Jobs {
//            get {
//                return ResourceManager.GetString("Back to All Jobs", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Back to List.
//        /// </summary>
//        public static string Back_to_List {
//            get {
//                return ResourceManager.GetString("Back to List", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Block.
//        /// </summary>
//        public static string Block {
//            get {
//                return ResourceManager.GetString("Block", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Cancel.
//        /// </summary>
//        public static string Cancel {
//            get {
//                return ResourceManager.GetString("Cancel", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Company.
//        /// </summary>
//        public static string Company {
//            get {
//                return ResourceManager.GetString("Company", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Connect.
//        /// </summary>
//        public static string Connect {
//            get {
//                return ResourceManager.GetString("Connect", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Connection Requests.
//        /// </summary>
//        public static string Connection_Requests {
//            get {
//                return ResourceManager.GetString("Connection Requests", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Connections.
//        /// </summary>
//        public static string Connections {
//            get {
//                return ResourceManager.GetString("Connections", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Continue with Facebook.
//        /// </summary>
//        public static string Continue_with_Facebook {
//            get {
//                return ResourceManager.GetString("Continue with Facebook", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Continue with Google.
//        /// </summary>
//        public static string Continue_with_Google {
//            get {
//                return ResourceManager.GetString("Continue with Google", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Create.
//        /// </summary>
//        public static string Create {
//            get {
//                return ResourceManager.GetString("Create", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Create Account.
//        /// </summary>
//        public static string Create_Account {
//            get {
//                return ResourceManager.GetString("Create Account", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Create Profile.
//        /// </summary>
//        public static string Create_Profile {
//            get {
//                return ResourceManager.GetString("Create Profile", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Current Roles.
//        /// </summary>
//        public static string Current_Roles {
//            get {
//                return ResourceManager.GetString("Current Roles", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Dashboard.
//        /// </summary>
//        public static string Dashboard {
//            get {
//                return ResourceManager.GetString("Dashboard", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Delete.
//        /// </summary>
//        public static string Delete {
//            get {
//                return ResourceManager.GetString("Delete", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Description.
//        /// </summary>
//        public static string Description {
//            get {
//                return ResourceManager.GetString("Description", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Details.
//        /// </summary>
//        public static string Details {
//            get {
//                return ResourceManager.GetString("Details", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Edit.
//        /// </summary>
//        public static string Edit {
//            get {
//                return ResourceManager.GetString("Edit", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Education.
//        /// </summary>
//        public static string Education {
//            get {
//                return ResourceManager.GetString("Education", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Email.
//        /// </summary>
//        public static string Email {
//            get {
//                return ResourceManager.GetString("Email", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Save Location.
//        /// </summary>
//        public static string h {
//            get {
//                return ResourceManager.GetString("h", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Home.
//        /// </summary>
//        public static string Home {
//            get {
//                return ResourceManager.GetString("Home", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Image.
//        /// </summary>
//        public static string Image {
//            get {
//                return ResourceManager.GetString("Image", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Jobs.
//        /// </summary>
//        public static string Jobs {
//            get {
//                return ResourceManager.GetString("Jobs", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Language.
//        /// </summary>
//        public static string Language {
//            get {
//                return ResourceManager.GetString("Language", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Location.
//        /// </summary>
//        public static string Location {
//            get {
//                return ResourceManager.GetString("Location", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Login.
//        /// </summary>
//        public static string Login {
//            get {
//                return ResourceManager.GetString("Login", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to LogOut.
//        /// </summary>
//        public static string LogOut {
//            get {
//                return ResourceManager.GetString("LogOut", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Manage User Roles.
//        /// </summary>
//        public static string Manage_User_Roles {
//            get {
//                return ResourceManager.GetString("Manage User Roles", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Messaging.
//        /// </summary>
//        public static string Messaging {
//            get {
//                return ResourceManager.GetString("Messaging", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to My Profile.
//        /// </summary>
//        public static string My_Profile {
//            get {
//                return ResourceManager.GetString("My Profile", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to No Archiveed Posts yet.
//        /// </summary>
//        public static string No_Archiveed_Posts_yet {
//            get {
//                return ResourceManager.GetString("No Archiveed Posts yet", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to No jobs available yet..
//        /// </summary>
//        public static string No_jobs_available_yet_ {
//            get {
//                return ResourceManager.GetString("No jobs available yet.", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to No pending requests..
//        /// </summary>
//        public static string No_pending_requests_ {
//            get {
//                return ResourceManager.GetString("No pending requests.", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to No Posts yet.
//        /// </summary>
//        public static string No_Posts_yet {
//            get {
//                return ResourceManager.GetString("No Posts yet", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to No Saved Posts yet.
//        /// </summary>
//        public static string No_Saved_Posts_yet {
//            get {
//                return ResourceManager.GetString("No Saved Posts yet", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Not Allowed.
//        /// </summary>
//        public static string Not_Allowed {
//            get {
//                return ResourceManager.GetString("Not Allowed", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Password.
//        /// </summary>
//        public static string Password {
//            get {
//                return ResourceManager.GetString("Password", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to People You May Know.
//        /// </summary>
//        public static string People_You_May_Know {
//            get {
//                return ResourceManager.GetString("People You May Know", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Posted Date.
//        /// </summary>
//        public static string Posted_Date {
//            get {
//                return ResourceManager.GetString("Posted Date", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Reject.
//        /// </summary>
//        public static string Reject {
//            get {
//                return ResourceManager.GetString("Reject", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Reply.
//        /// </summary>
//        public static string Reply {
//            get {
//                return ResourceManager.GetString("Reply", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Requests.
//        /// </summary>
//        public static string Requests {
//            get {
//                return ResourceManager.GetString("Requests", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Reset Password.
//        /// </summary>
//        public static string Reset_Password {
//            get {
//                return ResourceManager.GetString("Reset Password", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Save.
//        /// </summary>
//        public static string Save {
//            get {
//                return ResourceManager.GetString("Save", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Save Profile.
//        /// </summary>
//        public static string Save_Profile {
//            get {
//                return ResourceManager.GetString("Save Profile", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Save Review.
//        /// </summary>
//        public static string Save_Review {
//            get {
//                return ResourceManager.GetString("Save Review", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Saved.
//        /// </summary>
//        public static string Saved {
//            get {
//                return ResourceManager.GetString("Saved", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Saved jobs.
//        /// </summary>
//        public static string Saved_jobs {
//            get {
//                return ResourceManager.GetString("Saved jobs", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Saved Posts.
//        /// </summary>
//        public static string Saved_Posts {
//            get {
//                return ResourceManager.GetString("Saved Posts", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to See others&apos; profiles.
//        /// </summary>
//        public static string See_others__profiles {
//            get {
//                return ResourceManager.GetString("See others\' profiles", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to send.
//        /// </summary>
//        public static string send {
//            get {
//                return ResourceManager.GetString("send", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Send Reset Link.
//        /// </summary>
//        public static string Send_Reset_Link {
//            get {
//                return ResourceManager.GetString("Send Reset Link", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Set up your profile.
//        /// </summary>
//        public static string Set_up_your_profile {
//            get {
//                return ResourceManager.GetString("Set up your profile", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Sign Up.
//        /// </summary>
//        public static string Sign_Up {
//            get {
//                return ResourceManager.GetString("Sign Up", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Title.
//        /// </summary>
//        public static string Title {
//            get {
//                return ResourceManager.GetString("Title", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to UnArchived.
//        /// </summary>
//        public static string UnArchived {
//            get {
//                return ResourceManager.GetString("UnArchived", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Unblock.
//        /// </summary>
//        public static string Unblock {
//            get {
//                return ResourceManager.GetString("Unblock", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to UnSave.
//        /// </summary>
//        public static string UnSave {
//            get {
//                return ResourceManager.GetString("UnSave", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Update.
//        /// </summary>
//        public static string Update {
//            get {
//                return ResourceManager.GetString("Update", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Upgrade To Premium.
//        /// </summary>
//        public static string Upgrade_To_Premium {
//            get {
//                return ResourceManager.GetString("Upgrade To Premium", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Username.
//        /// </summary>
//        public static string Username {
//            get {
//                return ResourceManager.GetString("Username", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Video.
//        /// </summary>
//        public static string Video {
//            get {
//                return ResourceManager.GetString("Video", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to View Profile.
//        /// </summary>
//        public static string View_Profile {
//            get {
//                return ResourceManager.GetString("View Profile", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to View your profile.
//        /// </summary>
//        public static string View_your_profile {
//            get {
//                return ResourceManager.GetString("View your profile", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to What&apos;s on your mind?.
//        /// </summary>
//        public static string What_s_on_your_mind_ {
//            get {
//                return ResourceManager.GetString("What\'s on your mind?", resourceCulture);
//            }
//        }
        
//        /// <summary>
//        ///   Looks up a localized string similar to Your Review.
//        /// </summary>
//        public static string Your_Review {
//            get {
//                return ResourceManager.GetString("Your Review", resourceCulture);
//            }
//        }
//    }
//}
